<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/4/2
 * Time: 16:45
 */

namespace api\controllers;
use common\models\Article;
use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;


class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';
    public function actions()
    {
        $actions = parent::actions();
        unset($actions['index']);
        return $actions;
//        return parent::actions(); // TODO: Change the autogenerated stub
    }
    public function actionIndex()
    {
        $modelClass = $this->modelClass;
        return new ActiveDataProvider(
            [
                'query' => $modelClass::find() -> asArray(),
                'pagination' => ['pageSize' => 5]
            ]
        );
    }
    public function actionSearch()
    {
        return Article::find()->where(['like','title',$_POST['keyword']])->all();
    }
}